name: monble
description: A (local only) money management app for everyone. No backend, no internet connection required.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Isar dependencies
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # Riverpod dependencies
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.2

  # Other dependencies
  cupertino_icons: ^1.0.8
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Isar dependencies
  isar_generator: ^3.1.0+1

  # Riverpod dependencies
  riverpod_generator: ^2.3.3
  custom_lint: ^0.5.11
  riverpod_lint: ^2.1.1

  # Other dev dependencies
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Inter
       fonts:
         - asset: fonts/Inter-Thin.ttf
           weight: 100
         - asset: fonts/Inter-ExtraLight.ttf
           weight: 200
         - asset: fonts/Inter-Light.ttf
           weight: 300
         - asset: fonts/Inter-Regular.ttf
           weight: 400
         - asset: fonts/Inter-Medium.ttf
           weight: 500
         - asset: fonts/Inter-SemiBold.ttf
           weight: 600
         - asset: fonts/Inter-Bold.ttf
           weight: 700
         - asset: fonts/Inter-ExtraBold.ttf
           weight: 700
         - asset: fonts/Inter-Black.ttf
           weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
